### ISSUE TITLE
CommonAPI::DBus::DBusServiceRegistry::insertServiceNameMapping Segmentation fault

### ISSUE THREAD

**Issue by nboutin** [GENIVI/capicxx-core-runtime#11]
Hello,

I am base on CommonAPI 3.1.5.
I have a segmentation fault from DBusServiceRegistry.

It is a known issue corrected on more recent release ?

Regards

#0  0x419fe530 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_before_node (this=this@entry=0x18d18c, __n=1, __k="Lifecycle.Interface.LifecycleAPI", __code=__code@entry=2571721365) at /usr/include/c++/6.2.0/bits/hashtable.h:1417
#1  0x419fe5f0 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_find_node (__c=2571721365, __key="Lifecycle.Interface.LifecycleAPI", __bkt=<optimized out>, this=0x18d18c) at /usr/include/c++/6.2.0/bits/hashtable.h:634
#2  std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (this=this@entry=0x18d18c, __k="Lifecycle.Interface.LifecycleAPI") at /usr/include/c++/6.2.0/bits/hashtable.h:1294
#3  0x419f2e34 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, CommonAPI::DBus::DBusServiceRegistry::DBusUniqueNameRecord*> > >::find (__x="Lifecycle.Interface.LifecycleAPI", this=0x18d18c) at /usr/include/c++/6.2.0/bits/unordered_map.h:851

#4  CommonAPI::DBus::DBusServiceRegistry::insertServiceNameMapping (this=this@entry=0x18d148, dbusUniqueName=":1.93", dbusServiceName="Lifecycle.Interface.LifecycleAPI") at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusServiceRegistry.cpp:1345
#5  0x419f6ecc in CommonAPI::DBus::DBusServiceRegistry::onDBusServiceAvailable (this=this@entry=0x18d148, dbusServiceName="Lifecycle.Interface.LifecycleAPI", dbusServiceUniqueName=":1.93") at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusServiceRegistry.cpp:1122
#6  0x419f73e8 in CommonAPI::DBus::DBusServiceRegistry::onDBusDaemonProxyNameOwnerChangedEvent (this=0x18d148, affectedName="Lifecycle.Interface.LifecycleAPI", oldOwner="", newOwner=":1.93") at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusServiceRegistry.cpp:1113
#7  0x419c85a0 in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (__args#2=":1.93", __args#1="", __args#0="Lifecycle.Interface.LifecycleAPI", this=<optimized out>) at /usr/include/c++/6.2.0/functional:2136
#8  CommonAPI::Event<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::notifyListeners (eventArguments#2=":1.93", eventArguments#1="", eventArguments#0="Lifecycle.Interface.LifecycleAPI", this=0x18d30c) at /usr/include/CommonAPI-3.1/CommonAPI/Event.hpp:183
#9  CommonAPI::DBus::DBusEvent<CommonAPI::Event<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::handleSignalDBusMessage<0, 1, 2> (_message=..., this=0x18d30c) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/include/CommonAPI/DBus/DBusEvent.hpp:112
#10 CommonAPI::DBus::DBusEvent<CommonAPI::Event<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::onSignalDBusMessage (this=0x18d30c, _message=...) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/include/CommonAPI/DBus/DBusEvent.hpp:73
#11 0x419b7c04 in CommonAPI::DBus::notifyDBusSignalHandlers<std::unordered_map<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::pair<std::shared_ptr<std::recursive_mutex>, std::set<CommonAPI::DBus::DBusProxyConnection::DBusSignalHandler*, std::less<CommonAPI::DBus::DBusProxyConnection::DBusSignalHandler*>, std::allocator<CommonAPI::DBus::DBusProxyConnection::DBusSignalHandler*> > >, std::hash<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::equal_to<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const, std::pair<std::shared_ptr<std::recursive_mutex>, std::set<CommonAPI::DBus::DBusProxyConnection::DBusSignalHandler*, std::less<CommonAPI::DBus::DBusProxyConnection::DBusSignalHandler*>, std::allocator<CommonAPI::DBus::DBusProxyConnection::DBusSignalHandler*> > > > > > > (dbusHandlerResult=<synthetic pointer>, dbusMessage=..., signalEntry=<synthetic pointer>, dbusSignalHandlerstable=std::unordered_map with 1 elements = {...}) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusConnection.cpp:1433
#12 CommonAPI::DBus::DBusConnection::onLibdbusSignalFilter (this=0x1895d0, libdbusMessage=<optimized out>) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusConnection.cpp:1490
#13 0x41684784 in dbus_connection_dispatch (connection=0x189960) at /usr/src/debug/dbus/1.10.10-r0/dbus-1.10.10/dbus/dbus-connection.c:4858
#14 0x419b3894 in CommonAPI::DBus::DBusConnection::singleDispatch (this=0x1895d0) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusConnection.cpp:916
#15 0x419d3468 in CommonAPI::DBus::DBusMainLoop::dispatch (this=0x18c378, this@entry=0x419d33f4 <CommonAPI::DBus::DBusMainLoop::dispatch()+580>) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusMainLoop.cpp:546
#16 0x419d41c0 in CommonAPI::DBus::DBusMainLoop::doSingleIteration (this=0x419d33f4 <CommonAPI::DBus::DBusMainLoop::dispatch()+580>, this@entry=0x18c378, timeout=@0x41a476ec: -5261985641223916076) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusMainLoop.cpp:340
#17 0x419d4304 in CommonAPI::DBus::DBusMainLoop::run (this=0x18c378, timeoutInterval=@0x41a1ff18: 9223372036854775807) at /usr/src/debug/mm-common-api-c++-dbus/3.1.5.0+gitAUTOINC+eab540f476-r4/git/dist/CommonAPIDbus/src/src/CommonAPI/DBus/DBusMainLoop.cpp:210
#18 0x418afaf4 in std::execute_native_thread_routine (__p=0x1836f8) at ../../../../../../../../../../work-shared/gcc-6.2.0-r0/gcc-6.2.0/libstdc++-v3/src/c++11/thread.cc:83
#19 0x414360f0 in start_thread (arg=0xaf0fe410) at /usr/src/debug/glibc/2.24-r0/git/nptl/pthread_create.c:458
#20 0x413c0768 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:86 from /data2/corecrunch/TBM/rels/TBM2_L1_19082A_D/rootfs/lib/libc.so.6

**Comment by lutzbichler** [comment]
Please use a more recent version.
