### ISSUE TITLE
Some Tags point to bad repository

### ISSUE THREAD

**Issue by nori148** [GENIVI/capicxx-core-runtime#2]
I can't get old version of CommonAPI C++.
Tag 3.1.5-2.1.6 point to CommonAPI-Tools repository and
tag 2.1.5-2.0.0 point to CommonAPI-D-Bus one.

Thanks in advance.

**Comment by jeremiah** [comment]
Which older version of CommonAPI do you need? 

We're fixing up the legacy git repository at git.projects.genivi.org which may hold the older version you're looking for.

**Comment by nori148** [comment]
I'm looking for 2.1.6-p1.
`SRC_URI = "git://git.projects.genivi.org/ipc/common-api-runtime.git;tag=2.1.6-p1"`

**Comment by jeremiah** [comment]
I will look at that and see if I cannot find a fix.

**Comment by jeremiah** [comment]
I think I've fixed it, at least, it works for me. Please try these steps to see if it works for you using this repo: http://git.projects.genivi.org/?p=ipc/common-api-runtime;a=summary

``
1. git clone http://git.projects.genivi.org/ipc/common-api-runtime
2. cd common-api-runtime/
3. git checkout 2.1.6-p1
``

That will get you the tag manually. Your recipe should "just work" now. If it doesn't, please paste the error here and reopen this issue.

Thanks

**Comment by nori148** [comment]
I've succeeded in making common-api-runtime:
SRC_URI = "http://git.projects.genivi.org/ipc/common-api-runtime;notranch=1;tag=2.1.6-p1"
Thank you for your help.
If you can, please change repository name to ipc/common-api-runtime.git as before.
(and ipc/common-api-dbus-runtime.git)

**Comment by jeremiah** [comment]
Okay, I will try and do that. I had forgotten that the repos all had a .git at the end of them, I can fix that.

**Comment by jeremiah** [comment]
This should be complete now. Please test and let me know.

**Comment by nori148** [comment]
I've succeeded in making the original recipes of common-api-runtime and common-api-dbus-runtime.
Thank you very much.
