### ISSUE TITLE
Getting issue while cloning

### ISSUE THREAD

**Issue by biswaranjan402** [GENIVI/capicxx-core-runtime#20]
Hi,
I am following below  steps  for cloning the common-api-runtime but getting the fatal.
Can anyone help me on this.

$  git clone http://git.projects.genivi.org/ipc/common-api-runtime
Cloning into 'common-api-runtime'...
**fatal: unable to access 'http://git.projects.genivi.org/ipc/common-api-runtime/': Couldn't resolve host 'git.projects.genivi.org'**

also same issue if trying below :
$ git clone git://git.projects.genivi.org/ipc/common-api-runtime.git
Cloning into 'common-api-runtime'...
**fatal: Unable to look up git.projects.genivi.org (port 9418) (No such host is known. )**

Could you please help me.

Thank you.
Regards,
Biswa

**Comment by gunnarx** [comment]
> $ git clone http://git.projects.genivi.org/ipc/common-api-runtime

Do not use that address.  It is very old and outdated.  Use this one instead:

$ git clone https://github.com/GENIVI/capicxx-core-runtime

(in other words **this repository**, the one you commented on)
