### ISSUE TITLE
how to do  common api environment set up on windows

### ISSUE THREAD

**Issue by biswaranjan402** [GENIVI/capicxx-core-runtime#21]
Hi,
I need compiled dll and binaries for capi on windows.
Could any one help how to build on windows I am not finding any document on this.

Thanks in advance.

**Comment by lutzbichler** [comment]
There is not so much difference to building on Linux:
1. create a build directory
2. Call cmake  (aka: cmake ..)
3 Build the solution (aka: msbuild libcommonapi.sln)
