### ISSUE TITLE
error: ‘dbus_connection_send_with_reply_set_notify’ was not declared in this scope

### ISSUE THREAD

**Issue by sameerppradhan** [GENIVI/capicxx-core-runtime#23]
make giving the below error:
CommonAPI/DBus/DBusConnection.cpp:875:26: error: ‘dbus_connection_send_with_reply_set_notify’ was not declared in this scope
         libdbusSuccess = dbus_connection_send_with_reply_set_notify(connection_,

CommonAPI/DBus/DBusConnection.cpp:875:26: note: suggested alternative: ‘dbus_connection_send_with_reply_and_block’
         libdbusSuccess = dbus_connection_send_with_reply_set_notify(connection_,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          dbus_connection_send_with_reply_and_block
CMakeFiles/CommonAPI-DBus.dir/build.make:101: recipe for target 'CMakeFiles/CommonAPI-DBus.dir/src/CommonAPI/DBus/DBusConnection.cpp.o' failed
make[2]: *** [CMakeFiles/CommonAPI-DBus.dir/src/CommonAPI/DBus/DBusConnection.cpp.o] Error 1
CMakeFiles/Makefile2:106: recipe for target 'CMakeFiles/CommonAPI-DBus.dir/all' failed
make[1]: *** [CMakeFiles/CommonAPI-DBus.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Please help. Thanks

**Comment by lutzbichler** [comment]
You need to apply the patches (capicxx-dbus-runtime/tree/master/src/dbus-patches) to dbus before compiling capicxx-dbus-runtime.

**Comment by VishwanathB-123** [comment]
> You need to apply the patches (capicxx-dbus-runtime/tree/master/src/dbus-patches) to dbus before compiling capicxx-dbus-runtime.

Hi, 
I see a patch available for dbus-connection.c and dbus-connection.h, but build is failing at : DBus/DBusConnection.cpp .
How to apply patch here? Please let me know.

Error:
-------------
vishwa@ubuntu:~/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/build$ make
[  4%] Building CXX object CMakeFiles/CommonAPI-DBus.dir/src/CommonAPI/DBus/DBusConnection.cpp.o
/home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp: In member function ‘virtual bool CommonAPI::DBus::DBusConnection::sendDBusMessageWithReplyAsync(const CommonAPI::DBus::DBusMessage&, std::unique_ptr<CommonAPI::DBus::DBusProxyConnection::DBusMessageReplyAsyncHandler>, const CommonAPI::CallInfo*) const’:
/home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp:877:26: error: ‘dbus_connection_send_with_reply_set_notify’ was not declared in this scope; did you mean ‘dbus_connection_send_with_reply_and_block’?
  877 |         libdbusSuccess = dbus_connection_send_with_reply_set_notify(connection_,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          dbus_connection_send_with_reply_and_block
make[2]: *** [CMakeFiles/CommonAPI-DBus.dir/build.make:102: CMakeFiles/CommonAPI-DBus.dir/src/CommonAPI/DBus/DBusConnection.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:188: CMakeFiles/CommonAPI-DBus.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Patch command : 
vishwa@ubuntu:/$ sudo patch -d/ /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp  <~/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/dbus-patches/capi-dbus-add-send-with-reply-set-notify.patch
patching file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp
Hunk #1 FAILED at 3482.
1 out of 1 hunk FAILED -- saving rejects to file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp.rej
patching file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp
Hunk #1 FAILED at 229.
1 out of 1 hunk FAILED -- saving rejects to file /home/vishwa/vishwa/myCode/trydbus/capicxx-core-runtime/build/capicxx-dbus-runtime/src/CommonAPI/DBus/DBusConnection.cpp.rej
