### ISSUE TITLE
std::chrono::high_resolution_clock is used to calculate timeout interval

### ISSUE THREAD

**Issue by sandyatharman** [GENIVI/capicxx-core-runtime#4]
Hi,

Inside mainloop context implementation chrono::high_resolution_clock is used to calculate timeout interval which can easily result into a bug if the system time is updated by some other source [Ref: MainLoopContext::getCurrentTimeInMs]. Although high_resolution_clock is replaced by steady_clock in capicxx-dbus-runtime, but the same change seems to be missed out in capicxx-core-runtime. 

Please correct me if I am wrong.

Thanks & Regards,
Sandeep Arjun

**Comment by GenivivSOMEIPmaintainer** [comment]
Fixed with CommonAPI 3.1.12.1
