### ISSUE TITLE
Is it possible to use commonapi with in the same process? Do we have any configuration to achieve this.

### ISSUE THREAD

**Issue by ashokvasarla** [GENIVI/capicxx-core-runtime#6]
We are using COMMONAPI DBUS IPC with FIDL to communicate between process. Now I have new requirement, where I want to communicate within the process modules using the same FIDL. 
Is there any way to achieve this with-out posting via proxy to dbus daemon.

**Comment by GenivivSOMEIPmaintainer** [comment]
At the moment there is no easy way for that because the D-Bus binding always communicates via the D-Bus daemon. A special intraprocess-binding does not exist at the moment. With the SOME/IP binding the local communication is implemented via direct communication using unix domain sockets.

**Comment by AmirElAttar** [comment]
Hello
any updates on supporting using the same FIDL with dbus instead of vsomeip?
