### ISSUE TITLE
Comments on configuration file are not handled correctly

### ISSUE THREAD

**Issue by Kalabaza** [GENIVI/capicxx-core-runtime#7]
It seems comments on the configuration file are not handled correctly, since they are shown as errors on the log:

> [CAPI][ERROR] Missing '=' in key=value definition (line 6)

That is while using a configuration file like this:

```
[logging]
console=true
level=verbose

[proxy]
; comment
```

The solution to that problem, would be to simply ignore the comments while loading the configuration file (src/CommonAPI/IniFileReader.cpp, line 47):

```
// Ignore comments on the configuration file
std::size_t comment = line.find(';');
if (comment == 0) {
   continue;
}
```

**Comment by lutzbichler** [comment]
We have added this code and it will be released with the next CommonAPI release (> 3.1.12.6).
