### ISSUE TITLE
not possible to use an interface type with multiple bindings

### ISSUE THREAD

**Issue by TorstenGoerg** [GENIVI/capicxx-core-runtime#8]
Principally, multiple bindings can be used in parallel. But I found a surprising restriction. It seems to be not possible to make use of the same interface type with multiple bindings inside of one executable. I.e., the core runtime library is not prepared to provide an interface instance based on a particular binding and another instance of the same interface type based on another binding. In the methods 'Runtime::createProxyHelper' and 'Runtime::registerStubHelper' there is an algorithm that just iterates the availabe factories on a call of 'buildProxy' respectively 'registerService'. The first factory that can provide a proxy respectively stub object for the requested interface type randomly wins. It seems to be not possible to control the choice of a binding here. I.e., the configuration in "commonapi.ini" does not affect this choice. Principally, in the [proxy] and [stub] sections of "commonapi.ini" you can specify binding hints per address. But it seems that these hints only support the loading of dynamically linked libraries.
Have I overseen anything? Or is the use of the same interface type with multiple multiple really not supported yet?
If it is not supported I suggest to modify the runtime library implementation to make the binding choce controllable.

Regards,
Torsten Görg
itemis AG

**Comment by dprogm** [comment]
Hello Torsten,
we are using CommonAPI a lot and it's easily possible to use multiple bindings in one application. Indeed you control the binding to use with the address (**domain**:interface:**instance**) of your proxy or service you pass to the runtime; as a user you only have control over the domain and instance, the interface is implicitly provided by the generated code. [Here](https://github.com/GENIVI/capicxx-core-tools/wiki/Loading-Bindings-And-Libraries) is a comprehensive example that should make it clear how to configure your environment. The libraries are going to be loaded explicitly at runtime per request and not implicitly. Your executable doesn't have any compile time dependency to the binding (or at least shouldn't have).

**Comment by lutzbichler** [comment]
Yes, multiple bindings for the same interface within the same executable is not supported as the factories register themself for an interface, not for a set of interface instances.

**Comment by lutzbichler** [comment]
It is possible to use the same interface with multiple bindings. The problem are bindings like the dbus binding which provide an automatic translation between CommonAPI address and binding address, as these "consume" all creation/registration requests. In case of using dbus and  SOME/IP the workaround is to ensure the SOME/IP binding is loaded before the DBus binding. 

A full solution to this problem requires a mapping from instances to bindings per interface. As this was never requested, it is unlikely that this will be added (in the near future).
