### ISSUE TITLE
questions regarding the establishment of connections between clients and services

### ISSUE THREAD

**Issue by TorstenGoerg** [GENIVI/capicxx-core-runtime#9]
I have two questions about some details how connections between clients and services are established:

1. At least with the SomeIP binding, it seems to be possible to create a proxy object before the requested service is registered. Then the proxy is prebooked for a connection with the requested service in the routing component of vsomeip. As soon as the service gets available the proxy is conntected. I guess this behavior is the reason for the user code pattern for the proxy creation that is recommended by the CommonAPI UserGuide. This pattern suggests to call 'isAvailable()' cyclically until the service is really available before you call remote procedures via the proxy.
Is this feature of delayed connection establishment a general requirement that has to be fulfilled by any binding implementation to be compliant with the CommonAPI standard? As we implement our own bindings it is important to know which features we have to provide.

2. As far as I know, a proxy object is not automatically reconnected when the service instance it refers to is stopped and restarted. You have to create another proxy object to establish to connection to the restarted service instance again. Is that really correct?
If that is true it seems to be inconsistent in comparison to the feature described in my first question above. The connection is automatically established when the service instance gets available for the first time but not again later on?
Maybe I misunderstand or oversee something here. Please explain to me the ideas behind the way connections are established a little bit more in detail.

Regards,
Torsten Görg
itemis AG

**Comment by lutzbichler** [comment]
1. Yes, it is a general requirement. It must not matter, whether the corresponding service does already exist at the time a proxy is created.
2. The proxy is automatically reconnected.
